<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Bug condition exploration test for Quiz recorder field names mismatch.
 *
 * **Validates: Requirements 2.1, 2.2, 2.3**
 *
 * This test MUST FAIL on unfixed code - failure confirms the bug exists.
 * The test verifies that the recorder can initialize in Quiz question context
 * where field names are dynamically generated (e.g., q5:1_recording_id).
 *
 * @package    qtype_vidtreo
 * @copyright  2024 Vidtreo <https://vidtreo.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

global $CFG;
require_once($CFG->dirroot . '/question/engine/tests/helpers.php');
require_once($CFG->dirroot . '/question/type/vidtreo/tests/helper.php');
require_once($CFG->dirroot . '/question/type/vidtreo/question.php');

/**
 * Property 1: Bug Condition - Quiz Recorder Initialization Failure
 *
 * Tests that recorder initializes successfully in Quiz question context
 * where field names are dynamically generated by the question attempt API.
 *
 * @group qtype_vidtreo
 */
final class qtype_vidtreo_quiz_recorder_initialization_test extends advanced_testcase {

    /** @var int Number of property test iterations. */
    private const ITERATIONS = 10;

    /**
     * Reset the database and caches after each test.
     */
    protected function setUp(): void {
        parent::setUp();
        $this->resetAfterTest(true);
    }

    /**
     * Property 1: Bug Condition - Quiz Recorder Initialization
     *
     * **Validates: Requirements 2.1, 2.2, 2.3**
     *
     * For any Quiz question context where field names are dynamically generated,
     * the recorder SHALL successfully locate those fields and initialize correctly.
     *
     * This test uses a scoped PBT approach focusing on the concrete failing case:
     * Quiz question with slot 5, sequence 1, expecting field name q5:1_recording_id.
     *
     * EXPECTED OUTCOME ON UNFIXED CODE: Test FAILS (confirms bug exists)
     * EXPECTED OUTCOME ON FIXED CODE: Test PASSES (confirms bug is fixed)
     */
    public function test_property_quiz_recorder_initialization_with_dynamic_field_names(): void {
        global $PAGE;

        // Generate test cases: different question slots and sequences
        $testCases = $this->generateQuizContextTestCases(self::ITERATIONS);

        foreach ($testCases as $case) {
            $slot = $case['slot'];
            $sequence = $case['sequence'];

            // Create a mock question attempt with dynamic field names
            $qa = $this->createMockQuestionAttempt($slot, $sequence);

            // Get the renderer
            $renderer = $this->getRenderer();

            // Generate the HTML output
            $options = new question_display_options();
            $options->readonly = false;

            $html = $renderer->formulation_and_controls($qa, $options);

            // Assert 1: HTML contains the recorder container
            $this->assertStringContainsString(
                'data-region="vidtreo-recorder"',
                $html,
                "Recorder container should be present in HTML for slot {$slot}, sequence {$sequence}"
            );

            // Assert 2: HTML contains dynamically-named hidden fields
            $expectedRecordingIdField = "q{$slot}:{$sequence}_recording_id";
            $expectedPublicIdField = "q{$slot}:{$sequence}_public_id";
            $expectedDurationField = "q{$slot}:{$sequence}_duration";
            $expectedStatusField = "q{$slot}:{$sequence}_status";

            $this->assertStringContainsString(
                'name="' . $expectedRecordingIdField . '"',
                $html,
                "HTML should contain hidden field with dynamic name {$expectedRecordingIdField}"
            );

            $this->assertStringContainsString(
                'name="' . $expectedPublicIdField . '"',
                $html,
                "HTML should contain hidden field with dynamic name {$expectedPublicIdField}"
            );

            $this->assertStringContainsString(
                'name="' . $expectedDurationField . '"',
                $html,
                "HTML should contain hidden field with dynamic name {$expectedDurationField}"
            );

            $this->assertStringContainsString(
                'name="' . $expectedStatusField . '"',
                $html,
                "HTML should contain hidden field with dynamic name {$expectedStatusField}"
            );

            // Assert 3: Config passed to JavaScript includes fieldNames
            // Extract the config JSON from the HTML
            $configJson = $this->extractConfigFromHtml($html);
            $this->assertNotNull($configJson, "Config JSON should be present in HTML");

            $config = json_decode($configJson, true);
            $this->assertIsArray($config, "Config should be a valid JSON object");

            // CRITICAL ASSERTION: Config must include fieldNames for recorder to work
            $this->assertArrayHasKey(
                'fieldNames',
                $config,
                "Config MUST include 'fieldNames' array for recorder to locate dynamic fields (slot {$slot}, sequence {$sequence})"
            );

            // Assert 4: fieldNames in config match the actual field names
            $this->assertArrayHasKey('recordingId', $config['fieldNames']);
            $this->assertArrayHasKey('publicId', $config['fieldNames']);
            $this->assertArrayHasKey('duration', $config['fieldNames']);
            $this->assertArrayHasKey('status', $config['fieldNames']);

            $this->assertEquals(
                $expectedRecordingIdField,
                $config['fieldNames']['recordingId'],
                "Config fieldNames.recordingId should match actual field name"
            );

            $this->assertEquals(
                $expectedPublicIdField,
                $config['fieldNames']['publicId'],
                "Config fieldNames.publicId should match actual field name"
            );

            $this->assertEquals(
                $expectedDurationField,
                $config['fieldNames']['duration'],
                "Config fieldNames.duration should match actual field name"
            );

            $this->assertEquals(
                $expectedStatusField,
                $config['fieldNames']['status'],
                "Config fieldNames.status should match actual field name"
            );
        }
    }

    /**
     * Generate test cases for Quiz contexts with different slots and sequences.
     *
     * @param int $count Number of test cases to generate
     * @return array Array of test cases with 'slot' and 'sequence' keys
     */
    private function generateQuizContextTestCases(int $count): array {
        $cases = [];

        // Always include the concrete failing case from the design doc
        $cases[] = ['slot' => 5, 'sequence' => 1];

        // Generate additional random cases
        for ($i = 1; $i < $count; $i++) {
            $cases[] = [
                'slot' => rand(1, 20),
                'sequence' => rand(1, 5),
            ];
        }

        return $cases;
    }

    /**
     * Create a mock question attempt with dynamic field names.
     *
     * @param int $slot Question slot number
     * @param int $sequence Attempt sequence number
     * @return question_attempt Mock question attempt
     */
    private function createMockQuestionAttempt(int $slot, int $sequence): question_attempt {
        // Create a minimal question using the test helper
        $helper = new qtype_vidtreo_test_helper();
        $question = $helper->make_vidtreo_question();
        $question->maxrecordingtime = 120;
        $question->enablesourceswitching = true;
        $question->enablepause = true;
        $question->instructions = 'Test instructions';

        // Mock the get_qt_field_name method to return dynamic names
        $qaStub = $this->getMockBuilder(question_attempt::class)
            ->setConstructorArgs([$question, 1])
            ->onlyMethods(['get_qt_field_name', 'get_slot', 'get_last_qt_data', 'get_question'])
            ->getMock();

        $qaStub->method('get_slot')->willReturn($slot);

        $qaStub->method('get_qt_field_name')
            ->willReturnCallback(function($fieldname) use ($slot, $sequence) {
                return "q{$slot}:{$sequence}_{$fieldname}";
            });

        $qaStub->method('get_last_qt_data')->willReturn([]);
        
        $qaStub->method('get_question')->willReturn($question);

        return $qaStub;
    }

    /**
     * Get the qtype_vidtreo renderer.
     *
     * @return qtype_vidtreo_renderer
     */
    private function getRenderer(): qtype_vidtreo_renderer {
        global $PAGE;

        $PAGE->set_url('/');

        return $PAGE->get_renderer('qtype_vidtreo');
    }

    /**
     * Extract config JSON from HTML output.
     *
     * @param string $html HTML output from renderer
     * @return string|null Config JSON string or null if not found
     */
    private function extractConfigFromHtml(string $html): ?string {
        // Look for data-config attribute in the recorder container
        if (preg_match('/data-config="([^"]+)"/', $html, $matches)) {
            return html_entity_decode($matches[1]);
        }

        // Alternative: look for config_json in template context
        if (preg_match('/data-config-json=\'([^\']+)\'/', $html, $matches)) {
            return $matches[1];
        }

        // Another alternative: config might be in a script tag
        if (preg_match('/<script[^>]*>.*?var\s+config\s*=\s*({[^}]+});/s', $html, $matches)) {
            return $matches[1];
        }

        return null;
    }
}
